### ISSUE TITLE
KBSecret's brew recipe does not respect system rbenv

### ISSUE THREAD

**Issue by taohansen** [kbsecret/kbsecret#66]
* KBSecret 1.1.0
* Ruby 2.3.1

## Problem

Homebrew's KBSecret errors attempting to create a new password. Additionally does not path its own internal Ruby. 

## Replication

```
brew tap kbsecret/kbsecret
brew install kbsecret
kbsecret session new --team standard_library
kbsecret new login gandi
```

## Actual behavior

```
Ignoring ffi-1.9.23 because its extensions are not built.  Try: gem pristine ffi --version 1.9.23
Ignoring hitimes-1.2.6 because its extensions are not built.  Try: gem pristine hitimes --version 1.2.6
Ignoring inih-1.1.1 because its extensions are not built.  Try: gem pristine inih --version 1.1.1
/usr/local/Cellar/kbsecret/1.1.0/libexec/gems/inih-1.1.1/lib/inih.rb:3:in `require_relative': incompatible library version - /usr/local/Cellar/kbsecret/1.1.0/libexec/gems/inih-1.1.1/lib/ext/inih.bundle (fatal)
	from /usr/local/Cellar/kbsecret/1.1.0/libexec/gems/inih-1.1.1/lib/inih.rb:3:in `<top (required)>'
	from /Users/jackjennings/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/jackjennings/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/kbsecret/1.1.0/libexec/gems/kbsecret-1.1.0/lib/kbsecret/config.rb:4:in `<top (required)>'
	from /usr/local/Cellar/kbsecret/1.1.0/libexec/gems/kbsecret-1.1.0/lib/kbsecret.rb:7:in `require_relative'
	from /usr/local/Cellar/kbsecret/1.1.0/libexec/gems/kbsecret-1.1.0/lib/kbsecret.rb:7:in `<top (required)>'
	from /Users/jackjennings/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /Users/jackjennings/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /Users/jackjennings/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /usr/local/Cellar/kbsecret/1.1.0/libexec/gems/kbsecret-1.1.0/lib/kbsecret/cli/kbsecret-session:4:in `<main>'
```

**Comment by woodruffw** [comment]
Thanks for the report. Can you give me the output of `brew doctor`?

**Comment by jackjennings** [comment]
This error report was pulled off my laptop. Here's the messy brew doctor output:

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in the App Store.


Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/jackjennings/.pyenv/shims/python-config
  /Users/jackjennings/.pyenv/shims/python2-config
  /Users/jackjennings/.pyenv/shims/python2.7-config
  /Users/jackjennings/.pyenv/shims/python3-config
  /Users/jackjennings/.pyenv/shims/python3.4-config
  /Users/jackjennings/.pyenv/shims/python3.4m-config
  /Users/jackjennings/.pyenv/shims/python3.5-config
  /Users/jackjennings/.pyenv/shims/python3.5m-config

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libwkhtmltox.0.12.2.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/wkhtmltox/image.h
  /usr/local/include/wkhtmltox/pdf.h

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  libav

Warning: Your Xcode (9.0) is outdated.
Please update to Xcode 9.2 (or delete it).
Xcode can be updated from the App Store.

Warning: Calling 'depends_on :ant' is deprecated!
Use 'depends_on "ant"' instead.
/usr/local/Homebrew/Library/Taps/bramstein/homebrew-webfonttools/sfntly.rb:7:in `<class:Sfntly>'
Please report this to the bramstein/webfonttools tap!


Warning: Some keg-only formulae are linked into the Cellar.
Linking a keg-only formula, such as gettext, into the cellar with
`brew link <formula>` will cause other formulae to detect them during
the `./configure` step. This may cause problems when compiling those
other formulae.

Binaries provided by keg-only formulae may override system binaries
with other strange results.

You may wish to `brew unlink` these brews:
  qt
```

**Comment by woodruffw** [comment]
Are you having the same problem as @taohansen re: `rbenv`?

I'm not too familiar with `rbenv`, but my intuition is that the Homebrewed `ruby` and `gem` can conflict with it in all kinds of unpleasant ways (which aren't easy to resolve from just the formula's view).

Do other brewed gems (like `cocoapods` and `hub`) work for you?

**Comment by jackjennings** [comment]
(It's my stack trace in the original report)

`hub` has been written in Go for awhile now, but I do happen to have Cocoapods installed for some reason and it works fine.

**Comment by jackjennings** [comment]
I think that the issue is that I don't use homebrew to install Ruby—I use `rbenv` to manage multiple Ruby installations for various projects. It appears that installing `kbsecret` also installs the homebrew-managed `ruby`, which doesn't take precedence in my path for the `rbenv`-managed `ruby`.

With that said, when any of the CLI scripts try to pull `/usr/bin/env ruby` on the shebang line, it doesn't run the intended Ruby version with the required dependencies.

Not sure what the resolution is here.

**Comment by woodruffw** [comment]
> It appears that installing kbsecret also installs the homebrew-managed ruby, which doesn't take precedence in my path for the rbenv-managed ruby.

Yeah, I was afraid it would be something like that. I think the "solution" would be to give the homebrewed `ruby` higher precedence in your `PATH`, but that'll probably cause all sorts of other problems.



> Not sure what the resolution is here.

You could try installing `kbsecret` via `gem` (and uninstalling the `brew` version). That should work just fine with `rbenv`, although it doesn't come with the manpages installed.

**Comment by taohansen** [comment]
Does closed mean the issue is fixed?

**Comment by woodruffw** [comment]
"Closed" means that I don't have the ability to test this particular configuration, unfortunately. I've also rewritten the internals of the CLI over the last few releases, so I wasn't sure if the problem still applied to the latest release.

Have you tried using just the `gem` version, with the Homebrew version removed? I've had success with that on macOS.

**Comment by taohansen** [comment]
@jackjennings
